name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test
      run: mvn clean verify
      
    - name: Build Docker Image
      run: docker build -t inventario-api:latest .
      
    
    - name: Deploy to Kubernetes
      run: |
        # Configurar KUBECONFIG usando un secreto de GitHub
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/
        kubectl rollout status deployment/inventario-api